routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('index');
Route::get('/contacts', 'StockController@index')->name('contacts');

Route::get('/home', 'HomeController@home')->name('home')->middleware('auth');


Route::resource('products', 'ProductController');
//Route::resource('stocks', 'StockController');
Route::resource('categories', 'CategoryController');

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart/add/{id}', 'CartController@add')->name('cart.add');
Route::post('/cart/update', 'CartController@update')->name('cart.update');


Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart/add/{id}', 'CartController@add')->name('cart.add');
Route::post('/cart/update', 'CartController@update')->name('cart.update');

Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
Route::post('/checkout', 'CheckoutController@post')->name('checkout.post');
Route::get('/checkout/{order}', 'CheckoutController@view')->name('checkout.view');

Route::get('search', 'ProductController@search');


Route::get('/send-form', 'TelegramBotController@sendForm')->name('sendForm');


//Route::get('/updated-activity', 'TelegramBotController@updatedActivity');
Route::get('products-update', 'ProductController@productsUpdate');
Route::get('stock-update', 'StockController@stockUpdate');

Auth::routes(['register' => false]);


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


Route::middleware(['auth'])->group(function () {
    Route::get('/home/search', 'HomeController@search')->name('home.search')->middleware('auth');
    Route::post('/home/update', 'HomeController@updateStatus')->name('updateStatus')->middleware('auth');

});

Route::get('/{slug}', 'PageController@show');

resources/views/catalog.blade.php
@extends('layouts.app', [
    'title' => 'Каталог'
])
@section('content')
    @include('components.navbar.navbar_white')

    <section class="container mx-auto section-pad-bottom section-pad-top">
        <h1 class="mb-4">
            Каталог товаров
        </h1>
        <h2>
            Последнее обновление - <span class="text-primary underline">{{  date('d-m-Y')  }}</span>
        </h2>

        <div class="main w-full lg:w-4/5 mx-auto mt-6 mb-8">
            <div class="search">
                <div class="flex items-center border text-lg border-primary pr-4 w-full rounded-full">
                    <input type="text" name="catalogSearch" id="catalogSearch" placeholder="Поиск..."
                           class="w-full py-2 pl-4 rounded-full"/>
                    <span class="flex-shrink-0  text-sm py-1 px-2 rounded" id="clearSearch">
                               <img class=" h-6 mx-auto my-auto" src="{{ asset('/images/close.svg') }}">
                    </span>
                </div>

                <div class="overflow-y-auto results">
                    <div class=" text-decoration-none py-4" id="catalogSearchRes"></div>
                </div>
            </div>
        </div>


        <div class="mx-auto">
            <div class="md:flex mb-4 md:flex-wrap">
                @foreach($categories as $category)
                    <div class="w-full md:w-1/2 lg:w-1/4 mx-auto h-48">
                        <div
                            class="rounded-lg border-2 border-solid border-primary mx-3 px-6 pt-3 pb-3">
                            <a href="{{ route('categories.show', $category) }}"
                               class="block text-xl text-center font-bold"
                            >
                                <div class="flex-1">
                                    {{ $category->name }}
                                </div>
                            </a>
                            <div class="flex mt-8 mb-6">
                                <div class="line w-full border border-primary h-px border-white my-auto mr-4"></div>
                                <img class="h-10" src="{{ asset('/images/catalog.svg') }}">
                                <div class="line w-full border border-primary h-px border-white my-auto ml-4"></div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>

    <script type="application/javascript">

        $(document).ready(function () {


            $('#catalogSearch').on('keyup', function () {

                let search = $('#catalogSearch').val();
                // console.log(search.length)
                if (search.length > 3) {
                    $.ajax({

                        type: "GET",
                        url: '/search',
                        data: {search: $('#catalogSearch').val()},
                        success: function (data) {
                            $("#catalogSearchRes").empty();
                            $('.results').show()
                            $.each(data, function (i, item) {
                                let productUrl = '{{ route('products.index') }}/' + item.id;
                                $("#catalogSearchRes").append('<a class="w-full" href=" ' + productUrl + ' " >' +

                                    '<div class="flex w-full px-4 mt-2">\n' +
                                    '    <div class="flex-col">\n' +
                                    '        <div class="flex">' + item.name + '</div>\n' +
                                    '        <small class="flex text-primary">В наличии ' + item.qty + ' шт. </small>\n' +
                                    '    </div>\n' +
                                    '    <div class="flex ml-auto">от ' + item.price + '₽</div>\n' +
                                    '</div>' +
                                    '</a> <br/>');
                            });


                        }
                    });
                } else {
                    $("#catalogSearchRes").empty();
                    $('.results').hide()
                }
            });

            $("#clearSearch").click(function () {
                $("#catalogSearch").val('');
                $('.results').hide()
                $("#catalogSearchRes").empty();
            });


        });
    </script>


@endsection

resources/views/contacts.blade.php
@extends('layouts.app', [
    'title' => 'Адреса аптек'
])
@section('content')
    @include('components.navbar.navbar_white')

    <section class="container mx-auto section-pad-bottom section-pad-top">
        <h1  class="mb-4">
            Адреса наших аптек
        </h1>
        <h2>
            Последнее обновление - <span class="text-primary underline">{{  date('d-m-Y')  }}</span>
        </h2>



            <div class="mx-auto mt-6">
            <div class="flex flex-wrap mb-6 w-full">                    
                @foreach($stocks as $stock)
                        
                        <div class="bg-white px-3 lg:p-4 mb-6 w-full md:w-1/2 lg:w-1/3 xl:w-1/3">
                            <div class="w-full shadow rounded-xl ">
                                <div class="w-full">
                                    <img class="h-auto lg:h-56 w-full object-cover object-center rounded-t-xl"
                                    src="{{ ($stock->image) ? Voyager::image( $stock->image ) : asset('/images/placeholder.svg')}}"
                                    alt="">
                                </div>
    
                                <div class="pt-6 pb-12 px-6">
                                    <div class="text-xl lg:text-2xl font-bold mb-2 text-primary">
                                        {{ $stock->address }}
                                    </div>
                                    <div class="text-sm leading-relaxed block text-lg text-grey-600">
                                    <div>Телефон: <a class="underline text-primary" href="tel:">{{$stock->phone}}</a></div>
                                    <div>Режим работы: {{ $stock->work_hours }}</div>
                                    <div class="mt-2"><a href="{{ $stock->map_link }}" class="text-primary text-xl underline">На карте</a></div>
    
                                    </div>
                                </div>
                            </div>
                        </div>  
                    @endforeach
                </div>
            </div>
    </section>



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    @include('components.navbar.navbar_white')

    <section class="container mx-auto section-pad-bottom section-pad-top">
        <h1  class="mb-6">
            Админ-панель заказов
        </h1>

        <div class="mt-6">

            <div class="container mx-auto">

                <!-- component -->
                <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 pr-10 lg:px-8">
                    <div class="align-middle rounded-tl-lg rounded-tr-lg inline-block w-full py-4 overflow-hidden bg-white shadow-lg px-12">
                        <div class="flex justify-between">

                                <form action="{{ route('home.search') }}">
                                    <div class="flex w-full">
                                        <input type="text" name="search" class="w-4/5 border border-primary rounded px-3 relative " placeholder="Search">
                                        <button type="submit" class="ml-2 border border-primary py-2 px-4 w-32 rounded">Поиск</button>
                                    </div>

                                </form>
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf
                                <button class="text-primary" type="submit">Выход</button>
                            </form>
                        </div>

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                    </div>
                    <div class="align-middle inline-block min-w-full shadow overflow-hidden bg-white shadow-dashboard px-8 pt-3 rounded-bl-lg rounded-br-lg">
                        <table class="w-full table-auto my-8">
                            <thead>
                            <tr class="text-primary">
                                <th class="px-2 py-3 border-b-2 border-gray-300 text-left leading-4 text-primary tracking-wider">ID</th>
                                <th class="px-2 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 tracking-wider">Имя</th>
                                <th class="px-2 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 tracking-wider">Телефон</th>
                                <th class="px-2 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 tracking-wider">Адрес</th>
                                <th class="px-2 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 tracking-wider">Товары</th>
                                <th class="px-2 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 tracking-wider">Сумма</th>
                                <th class="px-2 py-3 border-b-2 border-gray-300 text-right text-sm leading-4 tracking-wider">Статус</th>
                            </tr>
                            </thead>
                            <tbody class="bg-white">
                            @foreach($orders as $order)
                            <tr class="border-b border-grey-500">
                                <td class="px-2 py-4">
                                    <div class="flex items-center">
                                        <div>
                                            <div class="text-sm leading-5 text-gray-800">#{{ $order->id }}</div>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-2 py-4">
                                    <div class="text-sm leading-5 text-blue-900">{{ $order->name }}</div>
                                </td>
                                <td class="px-2 py-4">
                                    {{ $order->phone }}</td>
                                <td class="px-2 py-4 text-sm leading-5">
                                    @if( ($order->address) )
                                        Доставка:  <span class="text-primary">{{ $order->address }}</span>

                                    @else
                                        Cамовывоз <span class="text-primary"> {{ $order->stock->name }} </span>
                                    @endif
                                </td>
                                <td class="px-2 py-4 text-sm leading-5"><div>
                                        @foreach( json_decode($order->cart) as $item )
                                            <div class="flex-column">
                                                <div>{{$item->name}}</div>
                                                <span class="text-primary"><small>Кол-во: {{ $item->quantity }} </small></span>
                                            </div>

                                        @endforeach

                                    </div></td>
                                <td class="px-2 py-4  text-sm leading-5"> {{ $order->total }} </td>
                                <td class="mx-auto py-4 text-sm leading-5">
                                    <div>
                                        <form class="flex-col text-center" method="POST" action="{{ route('updateStatus') }}">
                                            @csrf

                                            <input type="text" hidden name="id" value="{{ $order->id }}">
                                            <select name="status" class="block appearance-none w-full bg-white border border-primary text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" onchange="this.form.submit()">
                                                <option value disabled selected>
{{--                                                    @if($order->status == 'NEW') Новый--}}
{{--                                                    @elseif($order->status == 'IN_WORK') В работе--}}
{{--                                                    @elseif($order->status == 'FINISHED') Выполнен--}}
{{--                                                    @endif--}}
                                                    {{ $order->status }}
                                                </option>
                                                <option value="Новый">Новый</option>
                                                <option value="В работе">В работе</option>
                                                <option value="Выполнен">Выполнен</option>
                                            </select>
                                        </form>

                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $orders->links() }}

                    </div>
                </div>

            </div>

        </div>
    </section>



@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
    @include('components.navbar.navbar_primary')
    @include('components.intro')
    @include('components.locator')
    @include('components.sales')
    @include('components.form')
    @include('components.advantages')
@endsection

resources/views/page.blade.php
@extends('layouts.app', [
    'title' => $page->title,
    'description' => $page->description,
    'keywords' => $page->keywords
])
@section('content')
    @include('components.navbar.navbar_white')

    <section class="container mx-auto section-pad-bottom section-pad-top page">

        <div class="mt-6 mx-auto w-full lg:w-2/3 xl:w-4/5 text-lg">
            {!! $page->content !!}
        </div>
    </section>



@endsection